import pandas as pd

df = pd.read_csv('./Salaries .csv')

print(df.head())
print('-' * 100)
print(df.head(10))
print('-' * 100)
print(df.tail())
print('-' * 100)
print(df.tail(10))
print('-' * 100)
print(df.columns)
print('-' * 100)
print(df.shape)
print('-' * 100)
print(df.describe())
print('-' * 100)
df.info()
print('-' * 100)
print(df.dtypes)
print('-' * 100)
print(df.max())
print('-' * 100)
print(df.min())
print('-' * 100)
print(df.mean())
print('-' * 100)
print(df.median())
print('-' * 100)
print(df.std())
print('-' * 100)
print(df.isnull().sum())
print('-' * 100)


